import { StyleSheet, Platform } from "react-native";

export const COLORS = {
    bg: "#F8F9FB",
    bgCard: "#FFFFFF",
    bgCardAlt: "#EAF1FC",
    navy: "#0F1F3D",
    accent: "#3B7DD8",
    accentLight: "#7DAEF0",
    success: "#10B981",
    successLight: "rgba(16,185,129,0.12)",
    danger: "#EF4444",
    dangerLight: "rgba(239,68,68,0.10)",
    textPrimary: "#1A2333",
    textSecondary: "#6B7280",
    textMuted: "#9CA3AF",
    border: "#EEF1F5",
    borderLight: "#E2E8F0",
};

const cardShadow = {
    shadowColor: "#0F1F3D",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
};

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#0F1F3D" },
    scrollContent: { paddingBottom: 48 },

    hero: {
        paddingHorizontal: 20,
        paddingTop: Platform.OS === "ios" ? 56 : 40,
        paddingBottom: 36,
    },
    backRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 18,
    },
    backBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "rgba(255,255,255,0.10)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
        justifyContent: "center",
        alignItems: "center",
    },
    addBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#3B7DD8",
        justifyContent: "center",
        alignItems: "center",
    },
    heroLabel: {
        fontSize: 11,
        fontWeight: "700",
        letterSpacing: 2.5,
        color: "#7DAEF0",
        marginBottom: 6,
        textTransform: "uppercase",
    },
    heroTitle: {
        fontSize: 30,
        fontWeight: "800",
        color: "#FFFFFF",
        lineHeight: 34,
    },
    heroTitleAccent: { color: "#7DAEF0" },
    heroSubtitle: {
        fontSize: 13,
        color: "rgba(255,255,255,0.55)",
        marginTop: 8,
    },

    content: {
        flex: 1,
        backgroundColor: "#F8F9FB",
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        marginTop: -16,
        paddingTop: 22,
    },

    sectionLabel: {
        fontSize: 11,
        fontWeight: "800",
        letterSpacing: 1.2,
        color: "#6B7280",
        textTransform: "uppercase",
        marginHorizontal: 20,
        marginBottom: 14,
    },

    favoriteCard: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        backgroundColor: "#FFFFFF",
        borderRadius: 18,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 12,
        ...cardShadow,
    },
    favoriteAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#EAF1FC",
        justifyContent: "center",
        alignItems: "center",
    },
    favoriteAvatarText: {
        fontSize: 18,
        fontWeight: "800",
        color: "#3B7DD8",
    },
    favoriteInfo: { flex: 1, minWidth: 0 },
    favoriteAlias: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1A2333",
    },
    favoriteAccount: {
        fontSize: 11,
        color: "#9CA3AF",
        marginTop: 3,
        letterSpacing: 0.5,
    },
    favoriteActions: { flexDirection: "row", gap: 8 },
    favoriteActionBtn: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: "#EAF1FC",
        justifyContent: "center",
        alignItems: "center",
    },
    favoriteActionBtnDanger: { backgroundColor: "rgba(239,68,68,0.10)" },
    favoriteActionBtnAccent: { backgroundColor: "#3B7DD8" },

    confirmRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        backgroundColor: "rgba(239,68,68,0.10)",
        borderRadius: 18,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 12,
    },
    confirmText: { flex: 1, fontSize: 13, color: "#EF4444", fontWeight: "600" },
    confirmBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10 },
    confirmBtnDanger: { backgroundColor: "#EF4444" },
    confirmBtnGhost: { backgroundColor: "rgba(255,255,255,0.6)" },
    confirmBtnText: { fontSize: 11, fontWeight: "700", color: "#fff" },
    confirmBtnTextGhost: { color: "#EF4444" },

    emptyState: {
        alignItems: "center",
        paddingVertical: 56,
        paddingHorizontal: 32,
        gap: 12,
    },
    emptyIcon: {
        width: 72,
        height: 72,
        borderRadius: 22,
        backgroundColor: "#EAF1FC",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 4,
    },
    emptyTitle: { fontSize: 18, fontWeight: "700", color: "#1A2333" },
    emptySubtitle: {
        fontSize: 13,
        color: "#6B7280",
        textAlign: "center",
        lineHeight: 19,
    },
    emptyCta: {
        marginTop: 8,
        backgroundColor: "#0F1F3D",
        borderRadius: 14,
        paddingHorizontal: 22,
        paddingVertical: 13,
    },
    emptyCtaText: { color: "#fff", fontWeight: "700", fontSize: 13 },

    loadingContainer: { paddingVertical: 60, alignItems: "center", gap: 12 },
    loadingText: { fontSize: 13, color: "#9CA3AF", fontWeight: "500" },

    errorBox: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(239,68,68,0.10)",
        borderRadius: 14,
        padding: 14,
        marginHorizontal: 16,
        marginBottom: 12,
    },
    errorBoxText: { flex: 1, fontSize: 13, color: "#EF4444", fontWeight: "600" },

    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15,31,61,0.45)",
        justifyContent: "flex-end",
    },
    modalSheet: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        paddingTop: 12,
        paddingHorizontal: 24,
        paddingBottom: 36,
    },
    modalHandle: {
        width: 40,
        height: 4,
        borderRadius: 2,
        backgroundColor: "#E2E8F0",
        alignSelf: "center",
        marginBottom: 22,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: "800",
        color: "#1A2333",
        marginBottom: 4,
    },
    modalSubtitle: {
        fontSize: 13,
        color: "#6B7280",
        marginBottom: 22,
    },
    modalLabel: {
        fontSize: 11,
        fontWeight: "700",
        color: "#6B7280",
        textTransform: "uppercase",
        letterSpacing: 1,
        marginBottom: 8,
        marginTop: 14,
    },
    modalInputWrap: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderWidth: 1.5,
        borderColor: "#EEF1F5",
        borderRadius: 14,
        paddingHorizontal: 14,
        height: 52,
        backgroundColor: "#F8F9FB",
    },
    modalInput: {
        flex: 1,
        fontSize: 15,
        color: "#1A2333",
        paddingVertical: 0,
    },
    modalError: {
        fontSize: 11,
        color: "#EF4444",
        marginTop: 8,
        fontWeight: "600",
    },
    modalSubmitBtn: {
        height: 54,
        borderRadius: 16,
        backgroundColor: "#0F1F3D",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 26,
    },
    modalSubmitBtnDisabled: { opacity: 0.5 },
    modalSubmitBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
    modalCancelBtn: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 14,
    },
    modalCancelBtnText: { color: "#6B7280", fontWeight: "600", fontSize: 13 },
});