import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const COLORS = {
  navy:        "#0F1F3D",
  navyLight:   "#1A3260",
  accent:      "#3B7DD8",
  bg:          "#F0F2F5",
  white:       "#FFFFFF",
  success:     "#1A6E46",
  successBg:   "#EAF7F0",
  danger:      "#C0392B",
  dangerBg:    "#FDECEA",
  warning:     "#B7791F",
  warningBg:   "#FEF6E4",
  infoBg:      "#EAF3FB",
  info:        "#185FA5",
  textPrimary: "#111827",
  textMuted:   "#6B7280",
  border:      "#EEF1F5",
};

export const TABS = [
  { key: "all",      label: "Todos" },
  { key: "deposit",  label: "Depósitos" },
  { key: "withdraw", label: "Retiros" },
  { key: "transfer", label: "Transferencias" },
];

export const TX_TYPE_MAP = {
  deposit:  { label: "Depósito recibido",      icon: "arrow-down-left",  iconName: "arrow-down-left-outline",  bg: COLORS.successBg, color: COLORS.success  },
  withdraw: { label: "Retiro realizado",        icon: "arrow-up-right",   iconName: "arrow-up-outline",          bg: COLORS.dangerBg,  color: COLORS.danger   },
  transfer: { label: "Transferencia enviada",   icon: "swap-horizontal",  iconName: "swap-horizontal-outline",   bg: COLORS.infoBg,    color: COLORS.info     },
  received: { label: "Transferencia recibida",  icon: "refresh",          iconName: "repeat-outline",            bg: COLORS.infoBg,    color: COLORS.info     },
};

export const styles = StyleSheet.create({
  container:        { flex: 1, backgroundColor: COLORS.navy },
  header:           { backgroundColor: COLORS.navy, paddingHorizontal: 20, paddingBottom: 24 },
  headerTop:        { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  headerTitle:      { color: "#fff", fontSize: 18, fontWeight: "600" },
  iconBtn:          { width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(255,255,255,0.1)", justifyContent: "center", alignItems: "center" },
  balanceRow:       { marginBottom: 16 },
  balanceLabel:     { color: "rgba(255,255,255,0.5)", fontSize: 10, letterSpacing: 1, marginBottom: 4 },
  balanceAmount:    { color: "#fff", fontSize: 28, fontWeight: "700", letterSpacing: -0.5 },
  balanceSub:       { color: "rgba(255,255,255,0.4)", fontSize: 12, marginTop: 2 },
  pillsRow:         { flexDirection: "row", gap: 10 },
  pill:             { flex: 1, backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 12, padding: 12, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 0.5, borderColor: "rgba(255,255,255,0.1)" },
  pillDotGreen:     { width: 8, height: 8, borderRadius: 4, backgroundColor: "#4ADE80" },
  pillDotRed:       { width: 8, height: 8, borderRadius: 4, backgroundColor: "#F87171" },
  pillLabel:        { color: "rgba(255,255,255,0.45)", fontSize: 9, letterSpacing: 0.8 },
  pillAmount:       { color: "#fff", fontSize: 13, fontWeight: "600", marginTop: 2 },
  content:          { flex: 1, backgroundColor: COLORS.bg, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingTop: 16 },
  searchBar:        { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: COLORS.white, marginHorizontal: 16, marginBottom: 12, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 0.5, borderColor: COLORS.border },
  searchInput:      { flex: 1, fontSize: 14, color: COLORS.textPrimary, paddingVertical: 0 },
  tabsContainer:    { paddingHorizontal: 16, gap: 6, marginBottom: 14 },
  tab:              { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20, backgroundColor: COLORS.white, borderWidth: 0.5, borderColor: COLORS.border },
  tabActive:        { backgroundColor: COLORS.navy, borderColor: COLORS.navy },
  tabText:          { fontSize: 12, color: COLORS.textMuted, fontWeight: "500" },
  tabTextActive:    { color: "#fff" },
  sectionLabel:     { fontSize: 11, color: COLORS.textMuted, textTransform: "uppercase", letterSpacing: 0.8, marginHorizontal: 16, marginTop: 8, marginBottom: 6 },
  txItem:           { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, backgroundColor: COLORS.white, borderBottomWidth: 0.5, borderBottomColor: COLORS.border },
  txIcon:           { width: 40, height: 40, borderRadius: 12, justifyContent: "center", alignItems: "center" },
  txInfo:           { flex: 1, minWidth: 0 },
  txType:           { fontSize: 13, fontWeight: "600", color: COLORS.textPrimary },
  txAccount:        { fontSize: 11, color: COLORS.textMuted, marginTop: 2 },
  badge:            { alignSelf: "flex-start", paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6, marginTop: 4 },
  badgeDone:        { backgroundColor: COLORS.successBg },
  badgePending:     { backgroundColor: COLORS.warningBg },
  badgeText:        { fontSize: 9, fontWeight: "600" },
  badgeTextDone:    { color: COLORS.success },
  badgeTextPending: { color: COLORS.warning },
  txRight:          { alignItems: "flex-end" },
  txAmount:         { fontSize: 14, fontWeight: "700" },
  amountCredit:     { color: COLORS.success },
  amountDebit:      { color: COLORS.danger },
  txDate:           { fontSize: 10, color: COLORS.textMuted, marginTop: 2 },
  listContent:      { paddingTop: 4 },
  loadMore:         { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, padding: 16 },
  loadMoreText:     { color: COLORS.accent, fontSize: 13, fontWeight: "500" },
  emptyContainer:   { alignItems: "center", paddingTop: 60, gap: 8 },
  emptyTitle:       { fontSize: 16, fontWeight: "600", color: COLORS.textPrimary },
  emptyText:        { fontSize: 13, color: COLORS.textMuted },
  errorBox:         { flexDirection: "row", alignItems: "center", gap: 6, marginHorizontal: 16, marginBottom: 10, padding: 10, backgroundColor: COLORS.dangerBg, borderRadius: 10 },
  errorText:        { fontSize: 12, color: COLORS.danger, flex: 1 },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12, paddingTop: 60 },
  loadingText:      { fontSize: 13, color: COLORS.textMuted },
});