import { StyleSheet, Platform } from "react-native";

export const COLORS = {
    bg: "#F8F9FB",
    bgCard: "#FFFFFF",
    bgCardAlt: "#EAF1FC",

    navy: "#0F1F3D",
    navyDeep: "#071122",

    accent: "#3B7DD8",
    accentLight: "#7DAEF0",
    accentGlow: "rgba(59,125,216,0.08)",

    success: "#10B981",
    successLight: "rgba(16,185,129,0.12)",
    danger: "#EF4444",
    dangerLight: "rgba(239,68,68,0.10)",
    warning: "#B25E09",
    warningLight: "#FBF0DD",

    textPrimary: "#1A2333",
    textSecondary: "#6B7280",
    textMuted: "#9CA3AF",

    border: "#EEF1F5",
    borderLight: "#E2E8F0",
};

export const FONT = {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 18,
    xl: 22,
    xxl: 28,
    hero: 30,
};

const cardShadow = {
    shadowColor: "#0F1F3D",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
};

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#0F1F3D" },
    scrollContent: { paddingBottom: 48 },

    hero: {
        paddingHorizontal: 20,
        paddingTop: Platform.OS === "ios" ? 56 : 40,
        paddingBottom: 32,
    },
    backBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "rgba(255,255,255,0.10)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 18,
    },
    heroLabel: {
        fontSize: 11,
        fontWeight: "700",
        letterSpacing: 2.5,
        color: "#7DAEF0",
        marginBottom: 6,
        textTransform: "uppercase",
    },
    heroTitle: {
        fontSize: 30,
        fontWeight: "800",
        color: "#FFFFFF",
        lineHeight: 34,
    },
    heroTitleAccent: { color: "#7DAEF0" },
    heroSubtitle: {
        fontSize: 13,
        color: "rgba(255,255,255,0.55)",
        marginTop: 8,
    },

    content: {
        flex: 1,
        backgroundColor: "#F8F9FB",
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        marginTop: -16,
        paddingTop: 22,
    },

    section: { paddingHorizontal: 20, marginBottom: 22 },
    sectionLabelRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 12,
    },
    sectionLabel: {
        fontSize: 11,
        fontWeight: "800",
        letterSpacing: 1.2,
        color: "#6B7280",
        textTransform: "uppercase",
    },

    accountsRow: { gap: 12, paddingRight: 4 },
    accountOption: {
        width: 200,
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1.5,
        borderColor: "#EEF1F5",
        ...cardShadow,
    },
    accountOptionSelected: {
        borderColor: "#3B7DD8",
        backgroundColor: "rgba(59,125,216,0.08)",
    },
    accountOptionTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 14,
    },
    accountOptionType: {
        fontSize: 11,
        fontWeight: "700",
        letterSpacing: 1,
        color: "#9CA3AF",
        textTransform: "uppercase",
    },
    accountOptionRadio: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 2,
        borderColor: "#E2E8F0",
        justifyContent: "center",
        alignItems: "center",
    },
    accountOptionRadioSelected: { borderColor: "#3B7DD8" },
    accountOptionRadioDot: {
        width: 9,
        height: 9,
        borderRadius: 5,
        backgroundColor: "#3B7DD8",
    },
    accountOptionNumber: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1A2333",
        marginBottom: 4,
        letterSpacing: 1,
    },
    accountOptionBalance: {
        fontSize: 18,
        fontWeight: "800",
        color: "#1A2333",
    },
    accountOptionEmpty: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 20,
        alignItems: "center",
        ...cardShadow,
    },
    accountOptionEmptyText: {
        fontSize: 13,
        color: "#6B7280",
        textAlign: "center",
    },

    favoritesRow: { gap: 10, paddingRight: 4, paddingBottom: 2 },
    favoriteChip: { alignItems: "center", width: 72 },
    favoriteAvatar: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: "#EAF1FC",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 6,
        borderWidth: 2,
        borderColor: "transparent",
    },
    favoriteAvatarSelected: {
        borderColor: "#3B7DD8",
        backgroundColor: "rgba(59,125,216,0.08)",
    },
    favoriteAvatarText: {
        fontSize: 18,
        fontWeight: "800",
        color: "#3B7DD8",
    },
    favoriteChipLabel: {
        fontSize: 11,
        color: "#6B7280",
        fontWeight: "600",
        textAlign: "center",
    },
    favoriteChipLabelSelected: { color: "#1A2333", fontWeight: "700" },
    addFavoriteChip: {
        width: 52,
        height: 52,
        borderRadius: 26,
        borderWidth: 1.5,
        borderColor: "#E2E8F0",
        borderStyle: "dashed",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 6,
    },

    inputCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        paddingHorizontal: 16,
        ...cardShadow,
    },
    inputRow: {
        flexDirection: "row",
        alignItems: "center",
        height: 56,
        gap: 10,
    },
    inputIcon: { width: 20, alignItems: "center" },
    textInput: {
        flex: 1,
        fontSize: 15,
        color: "#1A2333",
        paddingVertical: 0,
    },
    selectedFavoriteBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(16,185,129,0.12)",
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginTop: 10,
    },
    selectedFavoriteBannerText: {
        flex: 1,
        fontSize: 11,
        color: "#10B981",
        fontWeight: "600",
    },

    amountCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        paddingVertical: 20,
        alignItems: "center",
        ...cardShadow,
    },
    amountRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    amountPrefix: { fontSize: 28, fontWeight: "800", color: "#9CA3AF" },
    amountInput: {
        fontSize: 40,
        fontWeight: "800",
        color: "#1A2333",
        minWidth: 60,
        textAlign: "center",
        paddingVertical: 0,
    },
    amountCurrency: {
        fontSize: 13,
        color: "#9CA3AF",
        marginTop: 6,
        fontWeight: "600",
    },

    hintBox: {
        flexDirection: "row",
        gap: 10,
        backgroundColor: "#EAF1FC",
        borderRadius: 14,
        padding: 14,
        marginHorizontal: 20,
        marginBottom: 20,
    },
    hintText: {
        flex: 1,
        fontSize: 11,
        color: "#6B7280",
        lineHeight: 17,
    },
    errorBox: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(239,68,68,0.10)",
        borderRadius: 14,
        padding: 14,
        marginHorizontal: 20,
        marginBottom: 20,
    },
    errorBoxText: {
        flex: 1,
        fontSize: 13,
        color: "#EF4444",
        fontWeight: "600",
    },

    submitWrap: { paddingHorizontal: 20, marginTop: 4 },
    submitBtn: {
        height: 56,
        borderRadius: 16,
        backgroundColor: "#0F1F3D",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 8,
    },
    submitBtnDisabled: { opacity: 0.5 },
    submitBtnText: {
        color: "#FFFFFF",
        fontSize: 15,
        fontWeight: "700",
        letterSpacing: 0.3,
    },

    successWrap: {
        flex: 1,
        backgroundColor: "#F8F9FB",
        alignItems: "center",
        paddingTop: 64,
        paddingHorizontal: 28,
    },
    successIconWrap: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: "rgba(16,185,129,0.12)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 22,
    },
    successTitle: {
        fontSize: 22,
        fontWeight: "800",
        color: "#1A2333",
        marginBottom: 6,
    },
    successSubtitle: {
        fontSize: 13,
        color: "#6B7280",
        textAlign: "center",
        marginBottom: 28,
    },
    successAmount: {
        fontSize: 30,
        fontWeight: "800",
        color: "#1A2333",
        marginBottom: 6,
    },
    successCard: {
        width: "100%",
        backgroundColor: "#FFFFFF",
        borderRadius: 18,
        padding: 18,
        marginBottom: 18,
        ...cardShadow,
    },
    successRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#EEF1F5",
    },
    successRowLast: { borderBottomWidth: 0 },
    successRowLabel: { fontSize: 13, color: "#6B7280" },
    successRowValue: { fontSize: 13, fontWeight: "700", color: "#1A2333" },

    saveFavoriteBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        width: "100%",
        height: 50,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: "#3B7DD8",
        marginBottom: 12,
    },
    saveFavoriteBtnText: { color: "#3B7DD8", fontWeight: "700", fontSize: 13 },

    successActions: { width: "100%", gap: 10, marginTop: 4 },
    successPrimaryBtn: {
        height: 54,
        borderRadius: 16,
        backgroundColor: "#0F1F3D",
        alignItems: "center",
        justifyContent: "center",
    },
    successPrimaryBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
    successSecondaryBtn: {
        height: 54,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
    },
    successSecondaryBtnText: { color: "#6B7280", fontWeight: "700", fontSize: 15 },
});