export const sm = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(15,31,61,0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.lg,
  },
  card: {
    width: '100%',
    maxWidth: isTablet ? 440 : 400,
    backgroundColor: KB.navyMid,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: SPACING.lg,
    alignItems: 'center',
  },
  iconCircle: {
    width: scale(64),
    height: scale(64),
    borderRadius: scale(32),
    backgroundColor: KB.successBg,
    borderWidth: 1.5,
    borderColor: KB.success,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.md,
  },
  iconText: { color: KB.success, fontSize: scale(30), fontWeight: '800' },
  title: {
    fontSize: scale(19),
    fontWeight: '800',
    color: KB.white,
    marginBottom: 8,
    textAlign: 'center',
  },
  message: {
    fontSize: scale(13),
    color: KB.gray,
    textAlign: 'center',
    lineHeight: scale(19),
    marginBottom: SPACING.lg,
  },
});